version: '3'
services:
  checkout_backend:
    build: .
    image: danielvza/checkout:0.0.1
    environment:
      DB_HOST: checkout-db
      DB_PORT: 3306
      DB_DATABASE: checkout
      DB_USERNAME: root
      DB_PASSWORD: root
      KAFKA_QUEUE: checkout_topic
      BOOTSTRAP_SERVERS: BOOTSTRAP_SERVERS
      SECURITY_PROTOCOL: SASL_SSL
      SASL_MECHANIMS: PLAIN
      SASL_USERNAME: SASL_USERNAME
      SASL_PASSWORD: SASL_PASSWORD
      GROUP_ID: GROUP_ID
      QUEUE_CONNECTION: kafka
      STRIPE_SECRET: sk_test_51L1cwjHuFtteLT4Pz8NdbostNCeAjA94U0T2WTYioZvt6aZhhgGGYwtH0rg2PIvRAVd6uBvrNqGcZp1FXgGPibLS00GSbJH1XA
      CHECKOUT_URL: http://localhost:5000
      USERS_MS: http://users_ms:8000
    ports:
      - 8002:8000
    command: >
      sh -c "php artisan config:cache
      && php artisan serve --host=0.0.0.0"
  checkout_queue:
    build: .
    image: danielvza/checkout:0.0.1
    environment:
      DB_HOST: checkout-db
      DB_PORT: 3306
      DB_DATABASE: checkout
      DB_USERNAME: root
      DB_PASSWORD: root
      KAFKA_QUEUE: checkout_topic
      BOOTSTRAP_SERVERS: BOOTSTRAP_SERVERS
      SECURITY_PROTOCOL: SASL_SSL
      SASL_MECHANIMS: PLAIN
      SASL_USERNAME: SASL_USERNAME
      SASL_PASSWORD: SASL_PASSWORD
      GROUP_ID: GROUP_ID
      QUEUE_CONNECTION: kafka
      USERS_MS: http://users_ms:8000
    command: >
      sh -c "php artisan config:cache
      && php artisan queue:work"
