version: '3'
services:
  admin_backend:
    build: .
    image: danielvza/admin:0.0.2
    environment:
      DB_HOST: admin-db
      DB_PORT: 3306
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root
      KAFKA_QUEUE: admin_topic
      BOOTSTRAP_SERVERS: BOOTSTRAP_SERVERS
      SECURITY_PROTOCOL: SASL_SSL
      SASL_MECHANIMS: PLAIN
      SASL_USERNAME: SASL_USERNAME
      SASL_PASSWORD: SASL_PASSWORD
      GROUP_ID: GROUP_ID
      QUEUE_CONNECTION: kafka
      USERS_MS: http://users_ms:8000
    ports:
      - 8004:8000
    command: >
      sh -c "php artisan config:cache
      && php artisan serve --host=0.0.0.0"

  admin_queue:
    build: .
    environment:
      DB_HOST: admin-db
      DB_PORT: 3306
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root
      KAFKA_QUEUE: admin_topic
      BOOTSTRAP_SERVERS: BOOTSTRAP_SERVERS
      SECURITY_PROTOCOL: SASL_SSL
      SASL_MECHANIMS: PLAIN
      SASL_USERNAME: SASL_USERNAME
      SASL_PASSWORD: SASL_PASSWORD
      GROUP_ID: GROUP_ID
      QUEUE_CONNECTION: kafka
      USERS_MS: http://users_ms:8000
    command: >
      sh -c "php artisan config:cache
      && php artisan queue:work"
