apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: admin-backend
  name: admin-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin-backend
  template:
    metadata:
      labels:
        io.kompose.service: admin-backend
    spec:
      containers:
        - args:
            - sh
            - -c
            - php artisan config:cache && php artisan serve --host=0.0.0.0
          env:
            - name: BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: BOOTSTRAP_SERVERS
            - name: DB_DATABASE
              value: admin
            - name: DB_HOST
              value: admin-db
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: GROUP_ID
              value: myGroup
            - name: KAFKA_QUEUE
              value: admin_topic
            - name: QUEUE_CONNECTION
              value: kafka
            - name: SASL_MECHANIMS
              value: PLAIN
            - name: SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_PASSWORD
            - name: SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_USERNAME
            - name: SECURITY_PROTOCOL
              value: SASL_SSL
            - name: USERS_MS
              value: http://users_ms:8000
          image: danielvza/admin:0.0.1
          name: admin-backend
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../admin/docker-compose.prod.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: admin-backend
  name: admin-backend
spec:
  ports:
    - name: "8004"
      port: 8004
      targetPort: 8000
  selector:
    io.kompose.service: admin-backend
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: admin-queue
  name: admin-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin-queue
  template:
    metadata:
      labels:
        io.kompose.service: admin-queue
    spec:
      containers:
        - args:
            - sh
            - -c
            - php artisan config:cache && php artisan queue:work
          env:
            - name: BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: BOOTSTRAP_SERVERS
            - name: DB_DATABASE
              value: admin
            - name: DB_HOST
              value: admin-db
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: GROUP_ID
              value: myGroup
            - name: KAFKA_QUEUE
              value: admin_topic
            - name: QUEUE_CONNECTION
              value: kafka
            - name: SASL_MECHANIMS
              value: PLAIN
            - name: SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_PASSWORD
            - name: SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_USERNAME
            - name: SECURITY_PROTOCOL
              value: SASL_SSL
            - name: USERS_MS
              value: http://users_ms:8000
          image: admin-queue
          name: admin-queue
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
